"""controller api key auth

Revision ID: 31b79265ef4f
Revises: a7de87ff06c0
Create Date: 2026-06-26 11:45:08.576306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b79265ef4f'
down_revision = 'a7de87ff06c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unifi_controllers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_mode', sa.String(length=20), nullable=False, server_default='password'))
        batch_op.add_column(sa.Column('api_key_encrypted', sa.Text(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('password_encrypted',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unifi_controllers', schema=None) as batch_op:
        batch_op.alter_column('password_encrypted',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('api_key_encrypted')
        batch_op.drop_column('auth_mode')

    # ### end Alembic commands ###
