"""portal_bandwidth_retention

Revision ID: 77294d1415b1
Revises: 8553bbd7362f
Create Date: 2026-06-30 10:18:43.589030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77294d1415b1'
down_revision = '8553bbd7362f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_points_mac_address'))
        batch_op.create_index(batch_op.f('ix_access_points_mac_address'), ['mac_address'], unique=False)

    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_limit_down', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rate_limit_up', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_retention_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.drop_column('data_retention_days')
        batch_op.drop_column('rate_limit_up')
        batch_op.drop_column('rate_limit_down')

    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_points_mac_address'))
        batch_op.create_index(batch_op.f('ix_access_points_mac_address'), ['mac_address'], unique=True)

    # ### end Alembic commands ###
