"""user_tenant_memberships

Revision ID: cc6ed30e4b17
Revises: 749ffde38187
Create Date: 2026-06-30 12:05:53.917411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6ed30e4b17'
down_revision = '749ffde38187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tenant_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_user_tenant_membership')
    )
    with op.batch_alter_table('user_tenant_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_tenant_memberships_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_tenant_memberships_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tenant_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tenant_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_tenant_memberships_tenant_id'))

    op.drop_table('user_tenant_memberships')
    # ### end Alembic commands ###
